server:
  port: 8078
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: stomp

  # mustache
  mustache:
    enabled: true
    charset: UTF-8
    suffix": .html
    check-template-location: true
